#!/usr/bin/env bash

python run_all.py ~/projects/models/best_hgs_thesis/best_e49.torch ~/results/thesis/pdm/multilayer_old_data_incl49lm/models/4_best_e49.torch ~/projects/data/datasets/300w_1.05.h5 --random_seed 0 --gpu 0 --encoder ~/results/thesis/pdm/multilayer_old_data_incl49lm/encoders/encoder_49_4.torch --scheduler '{"name": "plateau", "patience": 5, "factor": 0.75}' --optimizer '{"name": "adam", "lr": 0.025}' --epochs 1000 --conf_params 1 0.1 --menpo ~/projects/data/datasets/menpo_1.05.h5 > /tmp/e49.txt &
python run_all.py ~/projects/models/best_hgs_thesis/best_e68.torch ~/results/thesis/pdm/multilayer_old_data_incl49lm/models/24_best_all.torch ~/projects/data/datasets/300w_1.05.h5 --random_seed 0 --gpu 1 --scheduler '{"name": "plateau", "patience": 10, "factor": 0.25}' --optimizer '{"name": "adam", "lr": 0.025}' --epochs 100 --conf_params 0.1 0.1 --menpo ~/projects/data/datasets/menpo_1.05.h5 > /tmp/e68.txt &
python run_all.py ~/projects/models/best_hgs_thesis/best_all.torch ~/results/thesis/pdm/multilayer_old_data_incl49lm/models/24_best_h49.torch ~/projects/data/datasets/300w_1.05.h5 --gpu 2 --random_seed 0 --encoder ~/results/thesis/pdm/multilayer_old_data_incl49lm/encoders/encoder_68_24.torch --variance_threshold 2 --scheduler '{"name": "plateau", "patience": 5, "factor": 0.75}' --optimizer '{"name": "adam", "lr": 0.025}' --epochs 50 --conf_params 0.1 0.1 --menpo ~/projects/data/datasets/menpo_1.05.h5 > /tmp/h49.txt &
python run_all.py ~/projects/models/best_hgs_thesis/best_h.torch ~/results/thesis/pdm/multilayer/models/5_best_h68.torch ~/projects/data/datasets/300w_1.05.h5 --random_seed 0 --gpu 3 --variance_threshold 3 --scheduler '{"name": "plateau", "patience": 10, "factor": 0.5}' --optimizer '{"name": "adam", "lr": 0.025}' --epochs 100 --conf_params 1 0.1 --menpo ~/projects/data/datasets/menpo_1.05.h5 > /tmp/h68.txt &
python run_all.py ~/projects/models/best_hgs_thesis/best_e.torch ~/results/thesis/pdm/multilayer4/models/13_best_h49.torch ~/projects/data/datasets/300w_1.05.h5 --random_seed 0 --gpu 4 --scheduler '{"name": "plateau", "patience": 10, "factor": 0.25}' --optimizer '{"name": "adam", "lr": 0.025}' --epochs 250 --conf_params 1 0.1 --menpo ~/projects/data/datasets/menpo_1.05.h5 > /tmp/e.txt &
python run_all.py ~/projects/models/best_hgs_thesis/best_h.torch ~/results/thesis/pdm/multilayer_old_data_incl49lm/models/24_best_all.torch ~/projects/data/datasets/300w_1.05.h5 --random_seed 0 --gpu 5 --variance_threshold 2 --scheduler '{"name": "plateau", "patience": 10, "factor": 0.25}' --optimizer '{"name": "adam", "lr": 0.025}' --epochs 1000 --conf_params 0.1 0.1 --menpo ~/projects/data/datasets/menpo_1.05.h5 > /tmp/h.txt &
python run_all.py ~/projects/models/best_hgs_thesis/best_all.torch ~/results/thesis/pdm/multilayer_old_data_incl49lm/models/24_best_h49.torch ~/projects/data/datasets/300w_1.05.h5 --random_seed 0 --gpu 6 --encoder ~/results/thesis/pdm/multilayer_old_data_incl49lm/encoders/encoder_68_24.torch --variance_threshold 2 --scheduler '{"name": "plateau", "patience": 5, "factor": 0.75}' --optimizer '{"name": "adam", "lr": 0.025}' --epochs 50 --conf_params 0.1 0.1 --menpo ~/projects/data/datasets/menpo_1.05.h5 > /tmp/49.txt &
python run_all.py ~/projects/models/best_hgs_thesis/best_68.torch ~/results/thesis/pdm/multilayer_old_data_incl49lm/models/24_best_h49.torch ~/projects/data/datasets/300w_1.05.h5 --random_seed 0 --gpu 7 --variance_threshold 2 --scheduler '{"name": "plateau", "patience": 25, "factor": 0.1}' --optimizer '{"name": "adam", "lr": 0.1}' --epochs 250 --menpo ~/projects/data/datasets/menpo_1.05.h5 > /tmp/68.txt &
python run_all.py ~/projects/models/best_hgs_thesis/best_all.torch ~/results/thesis/pdm/multilayer_old_data_incl49lm/models/24_best_h49.torch ~/projects/data/datasets/300w_1.05.h5 --random_seed 0 --gpu 0 --encoder ~/results/thesis/pdm/multilayer_old_data_incl49lm/encoders/encoder_68_24.torch --variance_threshold 2 --scheduler '{"name": "plateau", "patience": 5, "factor": 0.75}' --optimizer '{"name": "adam", "lr": 0.025}' --epochs 50 --conf_params 0.1 0.1 --menpo ~/projects/data/datasets/menpo_1.05.h5 > /tmp/all.txt &