#!/usr/bin/env bash

targetdir=$1
if [ -d $targetdir ]; then
    python main.py ~/projects/results/hg_49lm/models/1017_best_hard_noutline.torch ~/projects/results/pdm_per_category/models/91_best_hard_49.torch ~/projects/data/datasets/facial_landmarks_from_holmes_ceclm_68_split.h5 --epochs 1000 --optimizer '{"name":"adam","lr":0.01}' --scheduler '{"name":"plateau","patience":10,"factor":0.5}' --variance_threshold 1.0 --test_reduction sum --random_seed 0 --gpu 3 --prediction_target $targetdir/no_encoder/easy49.json
    python main.py ~/projects/results/hg_bad/2/models/12_best_model.torch ~/projects/results/pdm_best4categories/d5/models/final_pdm_20.torch ~/projects/data/datasets/facial_landmarks_from_holmes_ceclm_68_split.h5 --epochs 50 --optimizer '{"name": "adam", "lr": 0.05}' --conf_params 1 0.5 --random_seed 0 --gpu 0 --test_reduction mean --variance_threshold 15.0 --prediction_target $targetdir/no_encoder/easy68.json
    python main.py ~/projects/results/hg_49lm/models/743_best_hard_noutline.torch ~/projects/results/pdm_per_category/models/62_best_easy_49.torch ~/projects/data/datasets/facial_landmarks_from_holmes_ceclm_68_split.h5 --epochs 100 --optimizer '{"name":"adam","lr":0.025}' --conf_params 1 0.1 --variance_threshold 3.5 --test_reduction sum --random_seed 0 --gpu 3 --prediction_target $targetdir/no_encoder/hard49.json
    python main.py ~/projects/models/hg_alpha/alpha_hg.torch ~/projects/results/pdm_best4categories/d5/models/34_best_pdm_hard_68.torch ~/projects/data/datasets/facial_landmarks_from_holmes_ceclm_68_split.h5 --epochs 1000 --optimizer '{"name": "adam", "lr": 0.025}' --variance_threshold 0.5 --conf_params 1 0.1 --random_seed 0 --gpu 0 --test_reduction mean --prediction_target $targetdir/no_encoder/hard68.json
    python main.py ~/projects/results/hg_49lm/models/1017_best_hard_noutline.torch ~/projects/results/pdm_per_category/models/91_best_hard_49.torch ~/projects/data/datasets/facial_landmarks_from_holmes_ceclm_68_split.h5 --epochs 1000 --optimizer '{"name": "adam", "lr": 0.025}' --scheduler '{"name":"plateau","patience":50,"factor":0.9,"threshold":0.001}' --variance_threshold 1.0 --conf_params 1 0.1 --encoder --random_seed 0 --gpu 3 --prediction_target $targetdir/encoder/easy49.json
    python main.py ~/projects/results/hg_bad/2/models/12_best_model.torch ~/projects/results/pdm_best4categories/d5/models/final_pdm_20.torch ~/projects/data/datasets/facial_landmarks_from_holmes_ceclm_68_split.h5 --epochs 100 --optimizer '{"name": "adam", "lr": 0.01}' --scheduler '{"name":"plateau","patience":10,"factor":0.25}' --conf_params 1 0.1 --random_seed 0 --gpu 0 --test_reduction mean --encoder --test_reduction mean --prediction_target $targetdir/encoder/easy68.json
    python main.py ~/projects/results/hg_49lm/models/743_best_hard_noutline.torch ~/projects/results/pdm_per_category/models/91_best_hard_49.torch ~/projects/data/datasets/facial_landmarks_from_holmes_ceclm_68_split.h5 --random_seed 0 --variance_threshold 2.5 --epochs 100 --optimizer '{"name": "adam", "lr": 0.025}' --conf_params 1 0.1 --encoder --gpu 3 --prediction_target $targetdir/encoder/hard49.json
    python main.py ~/projects/models/hg_alpha/alpha_hg.torch ~/projects/results/pdm_best4categories/d5/models/15_best_pdm_hard_68.torch ~/projects/data/datasets/facial_landmarks_from_holmes_ceclm_68_split.h5 --epochs 100 --optimizer '{"name":"adam","lr":0.01}' --scheduler '{"name":"plateau","patience":50,"factor":0.9,"threshold":0.001}' --variance_threshold 0.5 --encoder --test_reduction mean --random_seed 0 --gpu 3 --prediction_target $targetdir/encoder/hard68.json
else
    echo "Invalid target";
fi